Repository neos/neos-ui, pull requests merged in 2019-07, with the labels that each got.

#2524 FEATURE: Expose CK widget and highlight plugins
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui/src/apiExposureMap.js
  yarn.lock
Labels: CKEditor

#2526 TASK: Add positioning helper to ckeditor api exposure
  packages/neos-ui/src/apiExposureMap.js
Labels: CKEditor, Enhancement

#2525 TASK: Remove old yarn lock files in sub packages
  .gitignore
  packages/babel-preset-neos-ui/yarn.lock
  packages/build-essentials/yarn.lock
  packages/jest-preset-neos-ui/yarn.lock
  packages/neos-ui-decorators/yarn.lock
  packages/neos-ui-editors/yarn.lock
  packages/neos-ui-extensibility/yarn.lock
  packages/neos-ui-views/yarn.lock
  packages/neos-ui/yarn.lock
Labels: Cleanup
