Repository neos/neos-ui, pull requests merged in 2019-05, with the labels that each got.

#2466 BUGFIX: Adding assets in asset lists not working
  packages/neos-ui-editors/src/Editors/AssetEditor/index.js
Labels: Bug, Critical

#2488 TASK: Remove deprecated legacy logger
  Classes/Service/NodePropertyValidationService.php
  Tests/Functional/Service/NodePropertyValidationServiceTest.php
Labels: Help wanted, Technical debt

#2501 TASK: Link commit message guideline in readme
  README.md
Labels: Documentation
