Repository neos/neos-ui, pull requests merged in 2019-03, with the labels that each got.

#2388 BUGFIX: Stop hotkeys when editing shadow dom editables
  package.json
  yarn.lock
Labels: Bug

#2382 BUGFIX: Add missing legacy formatting options
  packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.ts
Labels: Bug

#2385 FEATURE: Add support for asset sources in asset editor
  Resources/Private/Fusion/Backend/Root.fusion
  packages/neos-ui-backend-connector/src/Endpoints/Helpers.ts
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-editors/src/Editors/AssetEditor/index.js
  packages/neos-ui/src/manifest.dataloaders.js
Labels: Enhancement, Technical debt, UI & UX

#2402 BUGFIX: Show the hide before and after icon always
  Classes/Fusion/Helper/NodeInfoHelper.php
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
Labels: Bug

#2408 BUGFIX: Allow clicking top of the inspector tabs
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.css
  packages/react-ui-components/src/DropDown/__snapshots__/contents.spec.tsx.snap
  packages/react-ui-components/src/DropDown/contents.spec.tsx
  packages/react-ui-components/src/DropDown/contents.tsx
Labels: Bug

#2393 FEATURE: Allow redux store extensibility
  packages/neos-ui-redux-store/src/index.ts
Labels: Backend / Backend-API, Help wanted

#2383 FEATURE: Remember active tab in inspector
  packages/neos-ui/src/Containers/RightSideBar/Inspector/TabPanel/index.js
  packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
  packages/react-ui-components/src/Tabs/__snapshots__/tabs.spec.tsx.snap
  packages/react-ui-components/src/Tabs/tabs.tsx
Labels: Enhancement

#2430 BUGFIX: Make tabs work without setting ids
  packages/react-ui-components/src/Tabs/tabs.tsx
Labels: Bug
