Repository neos/neos-ui, pull requests merged in 2020-10, with the labels that each got.

#2794 BUGFIX: fix creating and moving nodes with tree preset activated
  Classes/Controller/BackendController.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Resources/Private/Fusion/Prototypes/Page.fusion
  packages/neos-ui-backend-connector/src/Endpoints/Helpers.ts
  packages/neos-ui-redux-store/src/CR/Nodes/helpers.ts
  packages/neos-ui-redux-store/src/CR/Nodes/index.ts
  packages/neos-ui-sagas/src/CR/NodeOperations/addNode.js
  packages/neos-ui-sagas/src/CR/NodeOperations/moveDroppedNode.js
  packages/neos-ui-sagas/src/CR/NodeOperations/pasteNode.js
  packages/neos-ui-sagas/src/UI/PageTree/index.js
  packages/neos-ui/src/Containers/ContentCanvas/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
Labels: Bug, Frontend / Frontend-API, UI & UX, hacktoberfest-accepted

#2803 TASK: Remove deprecated isDisabled Button prop
  packages/react-ui-components/src/Button/button.tsx
Labels: hacktoberfest-accepted

#2802 !!! TASK: Remove the legacy aloha configuration handling
  packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.ts
  packages/react-proptypes/src/alohaConfiguration.js
  packages/react-proptypes/src/alohaConfiguration.spec.js
  packages/react-proptypes/src/index.js
  packages/react-proptypes/src/propertyDefinition.js
Labels: hacktoberfest-accepted

#2806 BUGFIX: Fix NodeType filter regression
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
  packages/utils-helpers/src/urlWithParams.spec.js
  packages/utils-helpers/src/urlWithParams.ts
Labels: Bug, hacktoberfest-accepted
