Repository neos/neos-ui, pull requests merged in 2022-11, with the labels that each got.

#3239 BUGFIX: Adjust width of dropdown content
  Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
  packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/style.css
  packages/react-ui-components/src/DropDown/style.css
Labels: Bug, hacktoberfest-accepted

#3229 FEATURE: Regenerate UriPathSegment in the backend
  .yarn/cache/@sindresorhus-slugify-npm-2.1.0-9985cfc88a-b2411b597e.zip
  .yarn/cache/@sindresorhus-transliterate-npm-1.5.0-b03ef7b868-7a52b46421.zip
  .yarn/cache/escape-string-regexp-npm-5.0.0-a663e825ce-20daabe197.zip
  .yarn/cache/lodash.deburr-npm-4.1.0-ccda5a50b5-6e2012315c.zip
  Classes/Controller/BackendServiceController.php
  Configuration/Routes.Service.yaml
  Resources/Private/Fusion/Backend/Root.fusion
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-editors/package.json
  packages/neos-ui-editors/src/Editors/UriPathSegment/index.js
  packages/react-ui-components/src/IconButton/iconButton.tsx
  yarn.lock
Labels: hacktoberfest-accepted

#3249 BUGFIX: pin devDependencies in utils-helpers to local workspace dependency
  packages/utils-helpers/package.json
Labels: Bug

#3065 FEATURE: Adds pixel snapping support to aspect ratio cropping
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
Labels: Feature, 8.2

#3245 BUGFIX: Allow to copy node without edit privilege
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
Labels: Bug, 7.3

#3132 FEATURE: Improvements for the Node Creation Dialog
  packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeFilter.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/style.css
  packages/react-ui-components/src/Dialog/style.css
Labels: Feature, 8.2

#3227 FEATURE: Responsive grid UI
  .yarn/cache/caniuse-lite-npm-1.0.30001316-dad0042022-8a96ee89f5.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001431-6d607db8ef-bc8ab55cd1.zip
  packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/index.css
  packages/neos-ui-inspector/src/SecondaryInspector/index.js
  packages/neos-ui-inspector/src/SecondaryInspector/style.css
  packages/neos-ui/src/Containers/App.js
  packages/neos-ui/src/Containers/ContentCanvas/style.css
  packages/neos-ui/src/Containers/LeftSideBar/index.js
  packages/neos-ui/src/Containers/LeftSideBar/style.css
  packages/neos-ui/src/Containers/PrimaryToolbar/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/style.css
  packages/neos-ui/src/Containers/RightSideBar/index.js
  packages/neos-ui/src/Containers/RightSideBar/style.css
  packages/neos-ui/src/Containers/SecondaryToolbar/index.js
  packages/neos-ui/src/Containers/SecondaryToolbar/style.css
  packages/neos-ui/src/Containers/style.css
  yarn.lock
Labels: UI & UX, hacktoberfest-accepted, Feature

#3260 TASK: Remove unused DTO
  Classes/Domain/Dto/LoadTreeDto.php
Labels: 8.2

#3195 !!! BUGFIX: CKEditor now uses em for italic
  packages/neos-ui-ckeditor5-bindings/src/manifest.config.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/italicWithEm.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/italicWithEmEditing.js
Labels: next-major

#3252 BUGFIX: Load content tree without waiting for guest frame
  packages/neos-ui-guest-frame/src/initializeGuestFrame.js
  packages/neos-ui-sagas/src/CR/NodeOperations/reloadState.js
Labels: Bug, 7.3

#3275 BUGFIX: Make e2e tests run via docker again
  Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
  Tests/IntegrationTests/TestDistribution/composer.json
  Tests/IntegrationTests/e2e-docker.sh
Labels: Bug, 7.3
