Repository neos/neos-ui, pull requests merged in 2022-03, with the labels that each got.

#2785 BUGFIX: Reduce the number of NodeTypes to run policy check against #2784
  Classes/Service/NodePolicyService.php
Labels: hacktoberfest-accepted

#3076 TASK: Upgrade d3-scale to version 4.0.2
  package.json
  yarn.lock
Labels: dependencies, 5.3

#3085 TASK: Renames isEmpty helper to isNil
  packages/react-ui-components/src/SelectBox/selectBox.js
  packages/utils-helpers/src/index.ts
  packages/utils-helpers/src/isEmpty.spec.js
  packages/utils-helpers/src/isEmpty.ts
  packages/utils-helpers/src/isNil.spec.js
  packages/utils-helpers/src/isNil.ts
Labels: 5.3

#3072 TASK: Remove lodash.set
  package.json
  packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
  yarn.lock
Labels: dependencies, 5.3

#3074 TASK: Removes lodash.upperfirst
  package.json
  packages/build-essentials/package.json
  packages/build-essentials/src/styles/styleConstants.js
  packages/neos-ui-views/package.json
  packages/neos-ui/package.json
  yarn.lock
Labels: Cleanup, dependencies, 8.0

#3077 TASK: Update react-dev-utils to 7.0
  packages/neos-ui-extensibility/package.json
  yarn.lock
Labels: dependencies, 8.0

#3091 FEATURE: Adds restore button for user impersonation
  Resources/Private/Fusion/Backend/Root.fusion
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-redux-store/src/User/Impersonate/index.ts
  packages/neos-ui-redux-store/src/User/index.ts
  packages/neos-ui-sagas/src/UI/Impersonate/index.js
  packages/neos-ui-sagas/src/index.js
  packages/neos-ui-sagas/src/manifest.js
  packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/RestoreButtonItem.js
  packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
  packages/neos-ui/src/index.js
Labels: Feature, 8.0
