Repository neos/neos-ui, pull requests merged in 2023-07, with the labels that each got.

#3537 BUGFIX: Render RightSideBar components even if the sidebar is hidden
  packages/neos-ui/src/Containers/RightSideBar/index.js
Labels: Bug, 7.3

#3496 BUGFIX: Consider content role of reference node while calculating enabled state of add button
  packages/neos-ui-guest-frame/src/InlineUI/NodeToolbar/Buttons/AddNode/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeToolBar/index.js
Labels: Bug, 7.3

#3555 BUGFIX: 3223 ck plugin `editor.neos` not initialized
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
Labels: Bug, 7.3

#3558 BUGFIX: 3557 placeholder plugin with autoparagraph false
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.spec.js
  packages/neos-ui-ckeditor5-bindings/src/manifest.config.js
  packages/neos-ui-ckeditor5-bindings/src/placeholder.vanilla-css
  packages/neos-ui-ckeditor5-bindings/src/plugins/cleanupNeosInlineWrapper.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/cleanupNeosInlineWrapper.spec.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/neosPlaceholder.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/neosPlaceholder.vanilla-css
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.html
Labels: Bug, 7.3

#3487 BUGFIX: Perform additional search for links that look like externals or emails
  Resources/Private/Translations/de/Main.xlf
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ui-editors/src/Library/LinkInput.js
Labels: Bug, 7.3, next-patch

#3492 BUGFIX: Limit click-outside handling for dialogs to their semi-transparent overlay
  package.json
  packages/react-ui-components/package.json
  packages/react-ui-components/src/Dialog/DialogManager.spec.ts
  packages/react-ui-components/src/Dialog/DialogManager.ts
  packages/react-ui-components/src/Dialog/__snapshots__/dialog.spec.tsx.snap
  packages/react-ui-components/src/Dialog/dialog.spec.tsx
  packages/react-ui-components/src/Dialog/dialog.tsx
  webpack.config.js
  yarn.lock
Labels: Bug, 7.3, next-patch

#3535 BUGFIX: Ensure that only numerical property values are converted to integer
  Classes/Domain/Service/NodePropertyConversionService.php
  packages/neos-ui-editors/src/Editors/TextArea/index.js
  packages/neos-ui-editors/src/Editors/TextField/index.js
Labels: Bug, 7.3, next-patch

#3559 TASK: cleanup disabled autoparagraph mode
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.spec.js
  packages/neos-ui-ckeditor5-bindings/src/manifest.config.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/cleanupNeosInlineWrapper.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/cleanupNeosInlineWrapper.spec.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/disabledAutoparagraphMode.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
Labels: 7.3, Task, next-patch

#3564 BUGFIX: Use better fallback mechanism for input value of RangeEditor
  packages/neos-ui-editors/src/Editors/Range/index.js
Labels: Bug, 7.3, Regression

#3565 BUGFIX: #3495 dimension selector deactivate search-box
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/DimensionSelector.js
Labels: Bug, 8.3

#3530 9.0: Adjust to changed node path API
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0

#3572 BUGFIX: 3493 Disabled multiselectbox could be dragged and deleted
  packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
  packages/react-ui-components/src/MultiSelectBox_ListPreviewSortable_DraggableListPreviewElement/multiSelectBox_ListPreviewSortable_DraggableListPreviewElement.js
  packages/react-ui-components/src/SelectBox/selectBox.js
Labels: Bug, 7.3, next-patch

#3560 BUGFIX: Ensure that docker E2E tests run locally on 8.0 & 8.1
  Tests/IntegrationTests/Fixtures/1Dimension/discarding.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
  Tests/IntegrationTests/Fixtures/2Dimension/SitePackage/Resources/Private/Content/Resources/6791d1beca5fa4ab78f1b2b1a44d43692f99b5dc
  Tests/IntegrationTests/Fixtures/2Dimension/SitePackage/Resources/Private/Content/Resources/aac28f51e5ca842e2646e88e7d242ac3c27e1f25
  Tests/IntegrationTests/Fixtures/2Dimension/SitePackage/Resources/Private/Fusion/Root.fusion
  Tests/IntegrationTests/docker-compose.yaml
  Tests/IntegrationTests/utils.js
Labels: Bug, 8.0, 8.1, next-patch

#3561 BUGFIX: Ensure that docker E2E tests run locally on 8.2 & 8.3
  Makefile
  Tests/IntegrationTests/Fixtures/1Dimension/discarding.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/inspectorValidation.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
  Tests/IntegrationTests/Fixtures/2Dimension/SitePackage/Resources/Private/Content/Resources/6791d1beca5fa4ab78f1b2b1a44d43692f99b5dc
  Tests/IntegrationTests/Fixtures/2Dimension/SitePackage/Resources/Private/Content/Resources/aac28f51e5ca842e2646e88e7d242ac3c27e1f25
  Tests/IntegrationTests/Fixtures/2Dimension/SitePackage/Resources/Private/Fusion/Root.fusion
  Tests/IntegrationTests/docker-compose.yaml
  Tests/IntegrationTests/utils.js
Labels: Bug, 8.2, 8.3, next-patch

#3579 BUGFIX: 3531 Prevent closing of node creation dialog
  packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
  packages/react-ui-components/src/Dialog/DialogManager.spec.ts
  packages/react-ui-components/src/Dialog/DialogManager.ts
  packages/react-ui-components/src/Dialog/__snapshots__/dialog.spec.tsx.snap
  packages/react-ui-components/src/Dialog/dialog.spec.tsx
  packages/react-ui-components/src/Dialog/dialog.tsx
  packages/react-ui-components/src/Dialog/style.css
Labels: Bug, 7.3, Task, next-patch

#3585 TASK: Replace getService method with new buildService method to build service of a content repository
  Classes/Controller/BackendController.php
  Classes/Fusion/Helper/ContentDimensionsHelper.php
Labels: 9.0, Task
