Repository neos/neos-ui, pull requests merged in 2023-04, with the labels that each got.

#3443 TAKS: Remove todo
  esbuild.js
Labels: 8.3

#3451 FEATURE: Improve user experience for Dimension Switcher
  Tests/IntegrationTests/Fixtures/1Dimension/switchingDimensions.e2e.js
  Tests/IntegrationTests/pageModel.js
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/DimensionSelector.js
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/style.module.css
  packages/react-ui-components/src/SelectBox/selectBox.js
  packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js
  packages/react-ui-components/src/SelectBox_ListPreview/selectBox_ListPreview.js
  packages/react-ui-components/src/SelectBox_Option_SingleLine/__snapshots__/selectBox_Option_SingleLine.spec.js.snap
  packages/react-ui-components/src/SelectBox_Option_SingleLine/selectBox_Option_SingleLine.js
Labels: UI & UX, Feature, 8.3

#3457 TASK: Deprecate plow-js
  packages/neos-ui/src/apiExposureMap.js
  packages/neos-ui/src/deprecated-plow.js
Labels: 8.3, Task

#3442 Revert "BUGFIX: Make extensibility api compatible with esbuild alias"
  packages/neos-ui-extensibility/extensibilityMap.json
  packages/neos-ui-extensibility/src/shims/vendor/redux-saga-effects/index.js
Labels: 8.3

#3444 TASK: Restrict what is published to npm
  packages/neos-ui-extensibility/package.json
  packages/positional-array-sorter/package.json
Labels: 8.3, Task

#3460 TASK: Adjust code to stricter Value Objects
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/NodeCreated.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/FlowQueryOperations/NeosUiFilteredChildrenOperation.php
  Classes/Fusion/Helper/ContentDimensionsHelper.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/NodeCreationHandler/DocumentTitleNodeCreationHandler.php
Labels: 9.0, Task

#3459 BUGFIX: Some 9.0 fixes
  Classes/Domain/Model/Feedback/Operations/Redirect.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
  Classes/Domain/Model/ReferencingChangeInterface.php
  Classes/Domain/Service/NodePropertyConversionService.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/DataSources/NodeWithDependingPropertiesDataSource.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/NodeCreationHandler/ImagePropertyNodeCreationHandler.php
Labels: Bug, 9.0

#3440 FEATURE: Make document tree clickable
  Tests/IntegrationTests/Fixtures/1Dimension/treeMultiselect.e2e.js
  Tests/IntegrationTests/pageModel.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
  packages/react-ui-components/src/Tree/node.js
Labels: Feature, 8.3

#3463 FEATURE: Allow changing the base workspace of a workspace
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/Property.php
Labels: Feature, 9.0

#3449 TASK: Speed up jest from 1:47 to 7s by running one instance from the root
  .yarn/cache/builtin-modules-npm-1.1.1-209bbd4692-0fbf69ffe7.zip
  .yarn/cache/tslib-npm-1.14.1-102499115e-dbe628ef87.zip
  .yarn/cache/tslint-config-prettier-npm-1.18.0-34f66a9995-f0c548a7a5.zip
  .yarn/cache/tslint-npm-5.20.1-c3ddb1b8bc-b11ee16c01.zip
  .yarn/cache/tslint-react-npm-3.6.0-494143e833-4c6f3831af.zip
  .yarn/cache/tsutils-npm-2.29.0-a46b62a46d-5d681bab79.zip
  Makefile
  package.json
  packages/jest-preset-neos-ui/jest-preset.json
  packages/jest-preset-neos-ui/package.json
  packages/jest-preset-neos-ui/src/esbuildTransformer.js
  packages/neos-ts-interfaces/package.json
  packages/neos-ui-backend-connector/package.json
  packages/neos-ui-build/package.json
  packages/neos-ui-constants/package.json
  packages/neos-ui-containers/package.json
  packages/neos-ui-containers/src/InsertModeSelector/index.spec.js
  packages/neos-ui-contentrepository/package.json
  packages/neos-ui-decorators/package.json
  packages/neos-ui-decorators/src/neos.spec.js
  packages/neos-ui-editors/package.json
  packages/neos-ui-extensibility/package.json
  packages/neos-ui-guest-frame/package.json
  packages/neos-ui-i18n/package.json
  packages/neos-ui-inspector/package.json
  packages/neos-ui-inspector/src/SecondaryInspector/index.spec.js
  packages/neos-ui-redux-store/package.json
  packages/neos-ui-sagas/package.json
  packages/neos-ui-validators/package.json
  packages/neos-ui-views/package.json
  packages/neos-ui-views/src/NodeInfoView/index.spec.js
  packages/neos-ui/package.json
  packages/positional-array-sorter/package.json
  packages/react-proptypes/package.json
  packages/react-ui-components/.editorconfig
  packages/react-ui-components/.stylelintrc
  packages/react-ui-components/package.json
  packages/utils-helpers/package.json
  packages/utils-logger/package.json
  packages/utils-redux/package.json
  yarn.lock
Labels: 8.3, Task

#3456 TASK: #3097 allow module script plugins
  Classes/Domain/Service/StyleAndJavascriptInclusionService.php
Labels: 7.3, Task

#3454 TASK: Improve ckeditor plugin migration to Neos 8.2 and up #3452
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
Labels: 8.2, Task

#3468 Add try-catch in publishAction of BackendServiceController.php to...
  Classes/Controller/BackendServiceController.php
Labels: 9.0
