Repository neos/neos-ui, pull requests merged in 2023-03, with the labels that each got.

#3395 BUGFIX: wrong hover color for DateInput component
  packages/react-ui-components/src/DateInput/style.css
Labels: Bug, 7.3

#3405 TASK: Update jenkins scripts to support 9.0 branch in compile step
  Build/Jenkins/update-neos-ui-compiled.sh
Labels: 9.0, Task

#3402 BUGFIX: `yarn version` your current branch contains multiple versioning files; this isn't supported
  .yarnrc.yml
Labels: Bug, 8.2

#3396 FEATURE: Improve node creation dialog
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ui-containers/src/InsertModeSelector/index.js
  packages/neos-ui-containers/src/InsertModeSelector/style.css
  packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
Labels: Feature, 8.3

#3414 TASK: remove `Neos.Ui.NodeInfo.inBackend` in favour of `Neos.Node.inBackend`
  Classes/Fusion/Helper/NodeInfoHelper.php
  Resources/Private/Fusion/Prototypes/Page.fusion
  Resources/Private/Fusion/Prototypes/Shortcut.fusion
Labels: 9.0, Task

#3403 BUGFIX: #3401 Update and Pin `"@friendsofreactjs/react-css-themr": "~4.2.0"`
  .yarn/cache/@friendsofreactjs-react-css-themr-npm-4.1.0-4222a20411-8ec14acae3.zip
  .yarn/cache/@friendsofreactjs-react-css-themr-npm-4.2.1-3bac33f833-df2a7b913b.zip
  packages/neos-ui/package.json
  packages/react-ui-components/package.json
  yarn.lock
Labels: Bug, 8.3

#3420 BUGFIX: Remove usage of `Neos\ContentRepository\Core\SharedModel\User\UserId`
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/Service/PublishingService.php
Labels: Bug, 9.0

#3424 TASK: Adjust to cleaned up Content Subgraph API
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/FlowQueryOperations/NeosUiFilteredChildrenOperation.php
  Classes/FlowQueryOperations/SearchOperation.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0, Task

#3429 TASK: consistently use public readonly properties in value objects, instead of getters
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/Create.php
  Classes/Domain/Model/Changes/CreateAfter.php
  Classes/Domain/Model/Changes/CreateBefore.php
  Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php
  Classes/NodeCreationHandler/CreationDialogPropertiesCreationHandler.php
  Classes/NodeCreationHandler/DocumentTitleNodeCreationHandler.php
Labels: 9.0, Task

#3427 TASK: Fix order of node creation dialog SearchBar
  packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/style.module.css
Labels: 8.3, Task

#3432 9.0: BUGFIX: fix converting `reference` or `references` properties in `NodePropertyConverterService`
  Classes/Domain/Service/NodePropertyConverterService.php
Labels: Bug, 9.0

#3435 9.0 TASK: fix remaining nodeAggregateIdentifier -> nodeAggregateId
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/Property.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
Labels: 9.0

#3433 BUGFIX: flowQueryAction (js endpoint for `q()`) handle non-existing nodes gracefully
  Classes/Controller/BackendServiceController.php
Labels: Bug, 7.3

#3438 TASK: Define runtime CSS variables for plugins
  cssVariables.css
  packages/neos-ui/src/styleHostOnly.css
Labels: 7.3, Task

#3399 BUGFIX: `<Tabs>` add `onActiveTabChange` and use `activeTab` on initial render
  packages/react-ui-components/src/Tabs/panel.tsx
  packages/react-ui-components/src/Tabs/tabs.spec.tsx
  packages/react-ui-components/src/Tabs/tabs.tsx
Labels: Bug, 7.3

#3423 FEATURE: add new node creation dialog icons
  Resources/Public/Icons/create-above.svg
  Resources/Public/Icons/create-below.svg
  Resources/Public/Icons/create-inside.svg
  packages/neos-ui-containers/src/InsertModeSelector/index.js
  packages/neos-ui-containers/src/InsertModeSelector/style.module.css
Labels: Feature, 8.3
