Repository neos/neos-ui, pull requests merged in 2023-02, with the labels that each got.

#3352 BUGFIX: Remove initiatingUserId from node commands
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
Labels: Bug, 9.0

#3187 FEATURE: Linking referenced documents in the reference and references editor
  packages/neos-ui-editors/src/Editors/Reference/index.js
  packages/neos-ui-editors/src/Editors/References/index.js
  packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
  packages/react-ui-components/src/MultiSelectBox_ListPreviewSortable_DraggableListPreviewElement/multiSelectBox_ListPreviewSortable_DraggableListPreviewElement.js
  packages/react-ui-components/src/SelectBox/selectBox.js
  packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js
Labels: UI & UX, Feature, 8.3

#3341 BUGFIX: Stop click event propagation on selected element in select box header
  packages/neos-ui-editors/src/Editors/AssetEditor/index.js
  packages/neos-ui-editors/src/Editors/Reference/index.js
  packages/react-ui-components/src/SelectBox/selectBox.js
  packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js
Labels: Bug, UI & UX, Accessibility, 7.3

#3355 TASK: Run codestyle and JS unittests on Github
  .circleci/config.yml
  .github/workflows/build_and_test.yml
Labels: Tooling / Testing, 7.3

#3333 FEATURE: Add blockquote to selectable styles
  Resources/Private/Translations/de/Main.xlf
  Resources/Private/Translations/en/Main.xlf
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Document/Page.yaml
  packages/neos-ui-ckeditor5-bindings/src/manifest.config.js
  packages/neos-ui-ckeditor5-bindings/src/manifest.richtextToolbar.js
Labels: CKEditor, Feature, 8.3

#3368 BUGFIX: Adjust width of dropdown content
  Tests/IntegrationTests/Fixtures/1Dimension/selectBoxes.e2e.js
  packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/style.css
  packages/react-ui-components/src/DropDown/style.css
Labels: 7.3

#3376 BUGFIX: Fix error msg of CountValidator
  packages/neos-ui-validators/src/Count/index.spec.js
  packages/neos-ui-validators/src/Count/index.tsx
Labels: Bug, 8.0

#3371 BUGFIX: Fix npm releases & cleanup release process
  .yarn/cache/@neos-project-positional-array-sorter-npm-8.1.4-352c7e42cd-ce0648805b.zip
  Build/Jenkins/release-neos-ui.sh
  Build/adjust-extensibility-package.sh
  Build/bumpVersion.sh
  Build/createVersionFile.sh
  Makefile
  esbuild.js
  packages/neos-ui-extensibility/package.json
  packages/positional-array-sorter/package.json
  packages/react-ui-components/package.json
  packages/tsconfig.json
  packages/utils-helpers/src/getVersion.spec.js
  packages/utils-helpers/src/getVersion.ts
  yarn.lock
Labels: 8.2

#3387 TASK: Adding labels to PRs
  .github/workflows/add-pr-labels.yml
Labels: 7.3, Task

#3294 FEATURE: custom node deletion text
  packages/neos-ui/src/Containers/Modals/DeleteNode/index.js
Labels: UI & UX, Feature, 8.3

#3362 BUGFIX: Ensure that the link editor "anchor" field never receives `undefined`
  packages/neos-ui-editors/src/Library/LinkInputOptions.js
Labels: Bug, 8.3

#3304 BUGFIX: fix interdependent properties in node creation dialog
  .gitignore
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/inspector.e2e.js
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/DataSources/NodeWithDependingPropertiesDataSource.php
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Content/NodeWithDependingProperties.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/NodeWithDependingProperties/NodeWithDependingProperties.fusion
  Tests/IntegrationTests/docker-compose.yaml
  Tests/IntegrationTests/e2e-docker.sh
  Tests/IntegrationTests/pageModel.js
  packages/neos-ui-redux-store/src/UI/NodeCreationDialog/index.ts
  packages/neos-ui-sagas/src/CR/NodeOperations/addNode.js
  packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
  packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
  packages/neos-ui/src/preprocessNodeConfiguration.spec.js
  packages/neos-ui/src/preprocessNodeConfiguration.ts
Labels: Bug, 7.3
