Repository neos/neos-ui, pull requests merged in 2023-01, with the labels that each got.

#3327 BUGFIX: Show relogin dialog when remote action results in redirect to login page
  packages/neos-ui-backend-connector/src/FetchWithErrorHandling/index.ts
Labels: 7.3

#3324 BUGFIX: Make sure secondary inspector container does not overlap editors in node creation dialog
  packages/neos-ui/src/Containers/Modals/NodeCreationDialog/style.css
Labels: 7.3

#3323 BUGFIX: Make sure that validation errors show up after clicking "Create New" in node creation dialog
  packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
Labels: Bug, 7.3

#3336 BUGFIX: Colocate react-ui-components esm-build declarations and sources
  packages/react-ui-components/package.json
  packages/react-ui-components/src/SelectBox/selectBox.js
  packages/react-ui-components/tsconfig.esm.json
Labels: Bug, Extensibility, 7.3

#3338 BUGFIX: Distribute height between inspector tabs header and content dynamically
  packages/neos-ui/src/Containers/RightSideBar/Inspector/style.css
  packages/react-ui-components/src/Tabs/style.css
Labels: Bug, Accessibility, 7.3

#3321 BUGFIX: Position `tableCreationGrid` absolutely
  packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/TableButton.css
Labels: Bug, 7.3

#3337 BUGFIX: Reset focused fusion path to `null` whenever the edit-/preview-mode changes
  packages/neos-ui-redux-store/src/CR/Nodes/index.ts
Labels: Bug, Accessibility, 7.3

#3322 BUGFIX: Ensure that `<DropDown/>` closes only after the current call-stack has been processed
  packages/react-ui-components/src/DropDown/wrapper.spec.tsx
  packages/react-ui-components/src/DropDown/wrapper.tsx
Labels: 7.3

#3334 BUGFIX: Hide inline toolbar if current editPreviewMode is not an edit mode
  packages/neos-ui/src/Containers/ContentCanvas/index.js
Labels: Bug, 7.3

#3300 TASK: Update plow-js to v3.0.0
  .yarn/cache/plow-js-npm-2.2.0-f1a18ee2db-d09f1dcf03.zip
  .yarn/cache/plow-js-npm-3.0.0-3448dc4b49-ad59f0014b.zip
  packages/neos-ui-backend-connector/package.json
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui-contentrepository/package.json
  packages/neos-ui-editors/package.json
  packages/neos-ui-guest-frame/package.json
  packages/neos-ui-inspector/package.json
  packages/neos-ui-redux-store/package.json
  packages/neos-ui-sagas/package.json
  packages/neos-ui-validators/package.json
  packages/neos-ui-views/package.json
  packages/neos-ui/package.json
  packages/react-ui-components/package.json
  yarn.lock
Labels: Technical debt, 8.3

#3345 BUGFIX: Reset/Clear `<SelectNodeType/>`-dialog on apply
  packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
Labels: Bug, 7.3

#3349 BUGFIX: Remove initiatingUserId from createNode command
  Classes/Domain/Model/Changes/AbstractCreate.php
Labels: Bug, 9.0
