Repository neos/neos-ui, pull requests merged in 2023-05, with the labels that each got.

#3473 TASK: Remove incorrect license excerpt
  README.md
Labels: 8.3, Task

#3484 BUGFIX: InfoTableLayout style broken
  packages/neos-ui-views/src/NodeInfoView/style.css
Labels: Bug, 8.2

#3507 BUGFIX: CreationDialog hideable elements
  packages/neos-ts-interfaces/src/index.ts
  packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
Labels: Bug, 7.3
