Repository neos/neos-ui, pull requests merged in 2023-09, with the labels that each got.

#3613 TASK: Cosmetic changes to satisfy linter
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/Model/ReferencingChangeInterface.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0, Task

#3612 TASK: Adjust to overhauled command constructors
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Service/PublishingService.php
Labels: 9.0, Task

#3618 TASK: Neos 9.0 edit preview modes
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Resources/Private/Fusion/Prototypes/Page.fusion
  Resources/Private/Fusion/Prototypes/Shortcut.fusion
Labels: 9.0, Task, 9.0beta1

#3627 TASK: stabilize local bare metal e2e tests inside neos dev collection
  .circleci/config.yml
  Tests/IntegrationTests/Fixtures/1Dimension/discarding.e2e.js
  Tests/IntegrationTests/Fixtures/2Dimension/switchingSites.e2e.js
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.OneDimension/Configuration/Settings.yaml
  Tests/IntegrationTests/TestDistribution/setup.sh
  Tests/IntegrationTests/e2e-docker.sh
  Tests/IntegrationTests/start-neos-dev-instance.sh
  Tests/IntegrationTests/utils.js
Labels: 9.0, Task

#3628 TASK: Adjust to removed `NodeType::getName()`
  Classes/Fusion/Helper/NodeInfoHelper.php
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/Resources/Private/Fusion/Root.fusion
Labels: 9.0, Task

#3624 BUGFIX: Adjust to removed Neos WorkspaceName
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Fusion/Helper/WorkspaceHelper.php
Labels: Bug, 9.0

#3515 !!! TASK: 9.0 Set `nodeName` to null for regular created nodes
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: Bug, 9.0

#3632 TASK: Adjust to removed NodeTypeFallback
  Classes/ContentRepository/Service/NodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Feedback/Operations/NodeCreated.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Service/NodePolicyService.php
Labels: 9.0, Task
