Repository neos/neos-ui, pull requests merged in 2023-06, with the labels that each got.

#3498 BUGFIX: Properly pause mousetrap during inline editing
  packages/neos-ui-sagas/src/UI/Hotkeys/index.js
Labels: Bug, 7.3

#3504 BUGFIX: Add dirty-state highlighting to RangeEditor
  packages/neos-ui-editors/src/Editors/Range/index.js
  packages/neos-ui-editors/src/Editors/Range/style.css
Labels: Bug, 7.3

#3511 BUGFIX: Sort nodeCreationHandlers
  Classes/Domain/Model/Changes/AbstractCreate.php
Labels: Bug, 7.3

#3497 BUGFIX: Sync frame component location after in-frame navigation happened
  packages/react-ui-components/src/Frame/frame.tsx
Labels: Bug, 7.3

#3486 BUGFIX: Hide in-between drop targets in tree component unless there's a drag operation happening
  packages/react-ui-components/src/Tree/node.css
  packages/react-ui-components/src/Tree/reactDndScrollzoneFork.js
Labels: Bug, 7.3

#3510 BUGFIX: Fixes sidebar resizer on Chrome
  packages/neos-ui/src/Containers/LeftSideBar/style.css
Labels: Bug, 8.2

#3485 BUGFIX: Add primitive Root ErrorBoundary around whole UI
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ui/src/Containers/ErrorBoundary/index.tsx
  packages/neos-ui/src/Containers/ErrorBoundary/style.module.css
  packages/neos-ui/src/Containers/Root.js
Labels: Bug, 7.3

#3538 BUGFIX: Ensure that SecondaryInspector is always above UnappliedChanges-overlay
  Tests/IntegrationTests/Fixtures/1Dimension/imageEditor.e2e.js
  cssVariables.css
  packages/build-essentials/src/styles/styleConstants.js
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/AspectRatioDropDown/style.css
  packages/neos-ui-inspector/src/SecondaryInspector/style.css
Labels: Bug, 7.3

#3522 TASK: abstractCreate Make NodeName Obsolet
  Classes/Domain/Model/Changes/AbstractCreate.php
Labels: 9.0, Task

#3532 BUGFIX: Fix ckeditor inline mode `autoparagraph: false`
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Content/InlineHeadline.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/InlineHeadline/InlineHeadline.fusion
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.spec.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/.gitignore
  packages/neos-ui-ckeditor5-bindings/tests/manual/build.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.html
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.js
  yarn.lock
Labels: Bug, 7.3

#3547 8.0 upmerge
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Content/InlineHeadline.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/InlineHeadline/InlineHeadline.fusion
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.spec.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/.gitignore
  packages/neos-ui-ckeditor5-bindings/tests/manual/build.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.html
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.js
  yarn.lock
Labels: 8.0

#3548 Upmerge 8.1
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Content/InlineHeadline.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/InlineHeadline/InlineHeadline.fusion
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.spec.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/.gitignore
  packages/neos-ui-ckeditor5-bindings/tests/manual/build.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.html
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.js
  yarn.lock
Labels: 8.1

#3551 Upmerge 8.3
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Content/InlineHeadline.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Resources/Private/Fusion/Content/InlineHeadline/InlineHeadline.fusion
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.js
  packages/neos-ui-ckeditor5-bindings/src/cleanupContentBeforeCommit.spec.js
  packages/neos-ui-ckeditor5-bindings/src/plugins/inlineMode.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/.gitignore
  packages/neos-ui-ckeditor5-bindings/tests/manual/build.js
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.html
  packages/neos-ui-ckeditor5-bindings/tests/manual/index.js
Labels: 8.3

#3554 TASK: ignoreNeos8Artifacts
  .gitignore
Labels: 7.3, Task
