Repository neos/neos-ui, pull requests merged in 2023-12, with the labels that each got.

#3663 BUGFIX: Show full labels in nodetrees if possible
  packages/react-ui-components/src/Tree/node.module.css
Labels: Bug, 8.3

#3603 BUGFIX: Neos 8.2 plugins dont lower yield in plugins
  packages/neos-ui-extensibility/scripts/helpers/webpack.config.js
Labels: Bug, 8.2

#3672 TASK: Run acceptance tests with Windows and Firefox
  Makefile
Labels: 8.3, Task

#3595 BUGFIX: select box and dropdown contents not visible in elevated inspector
  packages/react-ui-components/src/DropDown/style.css
  packages/react-ui-components/src/SelectBox/style.css
Labels: Bug, 7.3

#3604 BUGFIX: Neos 8.3 plugins dont lower yield in plugins
  packages/neos-ui-extensibility-webpack-adapter/scripts/helpers/webpack.config.js
Labels: Bug, 8.3

#3536 BUGFIX: Disable asset search through asset editor when media browser is disabled
  packages/neos-ui-editors/src/Editors/AssetEditor/index.js
Labels: Bug, 7.3, next-patch

#3482 BUGFIX: Properly handle object identity DTOs in select box editor
  packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
  packages/neos-ui-editors/src/Editors/SelectBox/createSelectBoxValueStringFromPossiblyStrangeNodePropertyValue.spec.ts
  packages/neos-ui-editors/src/Editors/SelectBox/createSelectBoxValueStringFromPossiblyStrangeNodePropertyValue.ts
Labels: Bug, 7.3, next-patch

#3670 FEATURE: Allow grouping in DimensionSwitcher
  Tests/IntegrationTests/Fixtures/1Dimension/SitePackage/Configuration/Settings.yaml
  Tests/IntegrationTests/Fixtures/1Dimension/switchingDimensions.e2e.js
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/DimensionSelector.js
Labels: Feature, 8.4

#3665 FEATURE: Add workspace Sync button
  Classes/Controller/BackendServiceController.php
  Classes/Controller/TranslationTrait.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Configuration/Routes.Service.yaml
  Resources/Private/Fusion/Backend/Root.fusion
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ts-interfaces/src/index.ts
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-redux-store/src/CR/Workspaces/index.spec.js
  packages/neos-ui-redux-store/src/CR/Workspaces/index.ts
  packages/neos-ui-redux-store/src/CR/Workspaces/selectors.ts
  packages/neos-ui-redux-store/src/UI/Remote/index.ts
  packages/neos-ui-redux-store/src/UI/SyncWorkspaceModal/index.ts
  packages/neos-ui-redux-store/src/UI/index.ts
  packages/neos-ui-sagas/src/Publish/index.js
  packages/neos-ui-sagas/src/manifest.js
  packages/neos-ui/src/Containers/Modals/SyncWorkspaceDialog/index.js
  packages/neos-ui/src/Containers/Modals/SyncWorkspaceDialog/style.module.css
  packages/neos-ui/src/Containers/PrimaryToolbar/WorkspaceSync/WorkspaceSyncIcon.js
  packages/neos-ui/src/Containers/PrimaryToolbar/WorkspaceSync/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/WorkspaceSync/style.module.css
  packages/neos-ui/src/manifest.containers.js
Labels: Feature, 9.0

#3465 TASK: cleanup imports of components
  packages/neos-ui-containers/src/InsertModeSelector/index.js
  packages/neos-ui-editors/src/EditorEnvelope/index.js
  packages/neos-ui-editors/src/Editors/AssetEditor/index.js
  packages/neos-ui-editors/src/Editors/Boolean/index.js
  packages/neos-ui-editors/src/Editors/CKEditor/index.js
  packages/neos-ui-editors/src/Editors/CodeMirror/index.js
  packages/neos-ui-editors/src/Editors/Image/Components/ResizeControls/index.js
  packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
  packages/neos-ui-editors/src/Editors/SelectBox/SimpleSelectBoxEditor.js
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/AspectRatioDropDown/index.js
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
  packages/neos-ui-inspector/src/SecondaryInspector/index.js
  packages/neos-ui/src/Containers/Drawer/MenuItem/index.js
  packages/neos-ui/src/Containers/Drawer/MenuItemGroup/index.js
  packages/neos-ui/src/Containers/FlashMessages/FlashMessage/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
  packages/neos-ui/src/Containers/LeftSideBar/index.js
  packages/neos-ui/src/Containers/Modals/DeleteNode/index.js
  packages/neos-ui/src/Containers/Modals/DiscardDialog/index.js
  packages/neos-ui/src/Containers/Modals/InsertMode/index.js
  packages/neos-ui/src/Containers/Modals/KeyboardShortcutModal/index.js
  packages/neos-ui/src/Containers/Modals/NodeCreationDialog/index.js
  packages/neos-ui/src/Containers/Modals/NodeVariantCreationDialog/index.js
  packages/neos-ui/src/Containers/Modals/ReloginDialog/index.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/index.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeFilter.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeGroupPanel.js
  packages/neos-ui/src/Containers/Modals/SelectNodeType/nodeTypeItem.js
  packages/neos-ui/src/Containers/Modals/UnappliedChangesDialog/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/EditPreviewDropDown/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/UserDropDown/index.js
  packages/neos-ui/src/Containers/RightSideBar/Inspector/PropertyGroup/index.js
  packages/neos-ui/src/Containers/RightSideBar/Inspector/SelectedElement/index.js
  packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
  packages/neos-ui/src/Containers/RightSideBar/index.js
Labels: Technical debt, 8.3, Task, Wrong Branch
