Repository neos/neos-ui, pull requests merged in 2023-08, with the labels that each got.

#3589 TASK: Allow node 16
  package.json
Labels: 7.3, Task, next-patch

#3601 BUGFIX: 3594 reduce deprecation logs
  packages/neos-ui/src/deprecated-plow.js
Labels: Bug, 8.3

#3588 BUGFIX: Image cropper has incorrect height with 150% zoom
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
Labels: Bug, 7.3, next-patch

#3596 TASK: Add moment locales to have a localized DatePicker
  packages/react-ui-components/src/DateInput/dateInput.tsx
Labels: Bug, 8.2, Task, next-patch

#3592 TASK: remove test-cafe quick fix
  Tests/IntegrationTests/utils.js
Labels: Task, 8.1, next-patch

#3576 BUGFIX: 3574 initialize foreign referenced nodes
  packages/neos-ui/src/manifest.js
Labels: Bug, 7.3, next-patch
