Repository neos/neos-ui, pull requests merged in 2023-11, with the labels that each got.

#3657 TASK: Remove Shortcut Override
  Resources/Private/Fusion/Prototypes/Shortcut.fusion
Labels: 9.0, Task

#3659 BUGFIX: Feedbacks have null defaults for optional properties
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/ReloadDocument.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
Labels: Bug, 9.0

#3625 TASK: Adjust to renamed `NodeTypeConstraints`
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/ReloadDocument.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/FlowQueryOperations/NeosUiFilteredChildrenOperation.php
  Classes/FlowQueryOperations/SearchOperation.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0, Task

#3643 BUGFIX: #3182 betterErrorForGetContextOnNull
  Classes/Controller/BackendController.php
Labels: Bug, 7.3

#3651 BUGFIX: Allow float numbers in RangeEditor
  packages/neos-ui-editors/src/Editors/Range/index.js
Labels: Bug, 7.3, next-patch

#3662 BUGFIX: Make long nodetype names readable in the node infoview
  packages/neos-ui-views/src/NodeInfoView/index.js
  packages/neos-ui-views/src/NodeInfoView/style.module.css
Labels: Bug, 8.3

#3666 BUGFIX: Style scrollbar in inspector dropdowns
  packages/neos-ui/src/Containers/style.module.css
Labels: Bug, 8.3

#3667 TASK: Adjust to removal of `findChildNodeConnectedThroughEdgeName`
  Classes/Controller/BackendController.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
Labels: 9.0, Task
