Repository neos/neos-ui, pull requests merged in 2023-10, with the labels that each got.

#3617 BUGFIX: `Cannot read properties of null (reading 'parent')`
  packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
Labels: Bug, 7.3

#3640 TASK: cleanup node service
  Classes/ContentRepository/Service/NeosUiNodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/ReloadDocument.php
  Classes/Domain/Service/NodeTreeBuilder.php
  Classes/TypeConverter/ChangeCollectionConverter.php
Labels: 9.0, Task

#3629 TASK: Use new `Neos.Neos:Site` abstract NodeType
  Classes/Controller/BackendController.php
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.OneDimension/Resources/Private/Content/events.jsonl
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.TwoDimensions/Resources/Private/Content/events.jsonl
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/NodeTypes/Document/HomePage.yaml
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/Resources/Private/Fusion/Document/Page/HomePage.fusion
  Tests/IntegrationTests/e2e-docker.sh
  Tests/IntegrationTests/e2e.sh
Labels: 9.0, Task

#3642 TASK: Adjust to changes in `NodeType`
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
Labels: 9.0, Task

#3644 TASK: Add phpstan
  .circleci/config.yml
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/AbstractFeedback.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/Redirect.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
  Classes/Domain/Model/FeedbackCollection.php
  Classes/Domain/Model/FeedbackInterface.php
  Classes/Domain/Model/RenderedNodeDomAddress.php
  Classes/Domain/Service/ConfigurationRenderingService.php
  Classes/Domain/Service/StyleAndJavascriptInclusionService.php
  Classes/Domain/Service/UserLocaleService.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/Fusion/ExceptionHandler/PageExceptionHandler.php
  Classes/Fusion/Helper/ApiHelper.php
  Classes/Fusion/Helper/ContentDimensionsHelper.php
  Classes/Fusion/Helper/ContentDimensionsHelperInternalsFactory.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Fusion/Helper/PositionalArraySorterHelper.php
  Classes/Fusion/Helper/StaticResourcesHelper.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Classes/Fusion/RenderConfigurationImplementation.php
  Classes/Service/NodePolicyService.php
  Classes/Service/NodePropertyValidationService.php
  Classes/TypeConverter/ChangeCollectionConverter.php
  Classes/TypeConverter/UiDependentImageSerializer.php
  Configuration/Settings.yaml
  Tests/IntegrationTests/TestDistribution/composer.json
  phpstan.neon
Labels: 9.0, Task

#3646 Update README.md
  README.md
Labels: 9.0

#3645 TASK: Remove `CACHE_VERSION` and invalidate cache after each run
  .circleci/config.yml
  README.md
Labels: 9.0, Task

#3649 BUGFIX: Respect also min value in width of input field on RangeEditor
  packages/neos-ui-editors/src/Editors/Range/index.js
Labels: Bug, 7.3

#3647 FEATURE: 4622 - decouple out-of-band rendering from Fusion
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/View/OutOfBandRenderingCapable.php
  Classes/View/OutOfBandRenderingFusionView.php
  Classes/View/OutOfBandRenderingViewFactory.php
  Configuration/Settings.yaml
Labels: Feature, 9.0

#3656 BUGFIX: Apply multiple properties from inspector
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/FeedbackCollection.php
Labels: Bug, 9.0
