Repository neos/neos-ui, pull requests merged in 2024-09, with the labels that each got.

#3836 BUGFIX: Always bundle custom svgs instead of using `resource://` paths
  esbuild.js
  packages/neos-ui-containers/src/InsertModeSelector/index.js
  packages/neos-ui-containers/src/InsertModeSelector/resources/create-above.svg
  packages/neos-ui-containers/src/InsertModeSelector/resources/create-below.svg
  packages/neos-ui-containers/src/InsertModeSelector/resources/create-inside.svg
  packages/neos-ui-editors/src/Editors/Image/Components/PreviewScreen/index.js
  packages/neos-ui-editors/src/Editors/Image/resource/dummy-image.dataurl.svg
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
  packages/react-ui-components/esbuild.js
  packages/react-ui-components/src/Icon/resourceIcon.tsx
  packages/react-ui-components/src/Logo/index.js
  packages/react-ui-components/src/Logo/logo.svg
  packages/react-ui-components/src/Logo/resource/logo.svg
  packages/react-ui-components/src/Logo/style.module.css
  packages/react-ui-components/src/ResourceIcon/index.tsx
  packages/react-ui-components/src/ResourceIcon/style.module.css
  packages/react-ui-components/src/index.ts
Labels: Bug, 8.3

#3846 BUGFIX: 3839 ckeditor only save changes if (really) dirty
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-guest-frame/src/initializePropertyDomNode.js
Labels: Bug, 8.3

#3847 BUGFIX: Remove duplicate focus ckeditor border
  packages/neos-ui-guest-frame/src/style.module.css
Labels: Bug, 8.3

#3852 BUGFIX: Neos logo icon width
  packages/react-ui-components/src/ResourceIcon/style.module.css
Labels: Bug, 8.3

#3851 TASK: Use saucectl with configuration
  .circleci/config.yml
  .sauce/config1Dimension.yml
  .sauce/config2Dimension.yml
  .sauceignore
  Build/comment-acceptance-tests.sh
  Makefile
  Tests/IntegrationTests/e2e-saucelabs.sh
Labels: Task, 8.4

#3854 BUGFIX: Use CIRCLE_BRANCH when we are not triggered by a PR
  .circleci/config.yml
Labels: Bug, 8.4

#3856 BUGFIX: Prevent augmenter from applying data of multiple nodes into the same element
  Classes/Aspects/AugmentationAspect.php
Labels: Bug, 8.3

#3861 FIX: Sizing of icons in alerts
  packages/neos-ui/src/Containers/FlashMessages/FlashMessage/style.module.css
Labels: 8.4
