Repository neos/neos-ui, pull requests merged in 2024-11, with the labels that each got.

#3844 Adjustments to new Reference DTOs
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/NodeCreation/NodeCreationCommands.php
  Classes/Infrastructure/ContentRepository/CreationDialog/PromotedElementsCreationHandlerFactory.php
Labels: 9.0

#3881 TASK: Adjust to "serializable commands"
  Classes/Infrastructure/ContentRepository/ConflictsFactory.php
Labels: 9.0, Task

#3871 TASK: Adjust to Content Repository Privileges
  Classes/Application/ReloadNodes/ReloadNodesQueryHandler.php
  Classes/ContentRepository/Service/NeosUiNodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Classes/Infrastructure/Configuration/ConfigurationProvider.php
  Classes/Infrastructure/ContentRepository/ConflictsFactory.php
Labels: 9.0, Task

#3876 FEATURE: Automatically set nodemove strategy in core
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Configuration/NodeTypes.yaml
Labels: Feature, 9.0
