Repository neos/neos-ui, pull requests merged in 2024-10, with the labels that each got.

#3865 TASK: Dont use react inside `terminateDueToFatalInitializationError`
  packages/neos-ui/src/Containers/ErrorBoundary/style.module.css
  packages/neos-ui/src/System/terminateDueToFatalInitializationError.js
Labels: 9.0, Task

#3838 FEATURE: Extract workspace metadata and user-assignment to Neos
  Classes/Application/ReloadNodes/ReloadNodesQueryHandler.php
  Classes/Application/SyncWorkspace/SyncWorkspaceCommandHandler.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Classes/Infrastructure/Configuration/ConfigurationProvider.php
  Tests/IntegrationTests/Fixtures/1Dimension/discarding.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/syncing.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/treeMultiselect.e2e.js
  Tests/IntegrationTests/e2e-docker.sh
  Tests/IntegrationTests/e2e.sh
Labels: Feature, 9.0

#3860 BUGFIX: Trim leading and tailing whitespaces
  packages/neos-ui-editors/src/Library/LinkInput.js
Labels: Bug, 8.3

#3864 BUGFIX: Restore old Placeholder behavior to keep shown when focused
  .yarn/cache/@ckeditor-ckeditor5-engine-patch-dfc8c266c9-0ca241d6d2.zip
  package.json
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
  packages/neos-ui-ckeditor5-bindings/src/placeholder.vanilla-css
  patches/@ckeditor-ckeditor5-engine-npm-16.0.0-placeholder.patch
  yarn.lock
Labels: Bug, 8.3

#3868 TASK: Adjust to Add workspace content stream mapping to content graph projection
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Infrastructure/Configuration/ConfigurationProvider.php
Labels: 9.0, Task

#3858 TASK: migrate to new json node address
  Classes/Application/ChangeTargetWorkspace.php
  Classes/Application/ReloadNodes/NodeMap.php
  Classes/Application/ReloadNodes/ReloadNodesQueryHandler.php
  Classes/Application/ReloadNodes/ReloadNodesQueryResult.php
  Classes/ContentRepository/Service/NeosUiNodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Feedback/Operations/NodeCreated.php
  Classes/Domain/Model/Feedback/Operations/Redirect.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RemoveNode.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Service/NodeClipboard.php
  Classes/TypeConverter/ChangeCollectionConverter.php
  Tests/IntegrationTests/Fixtures/1Dimension/discarding.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/treeMultiselect.e2e.js
  packages/neos-ui-guest-frame/src/dom.js
  packages/neos-ui/src/manifest.js
Labels: 9.0, Task

#3867 BUGFIX: Fix hidden state evaluation
  Classes/Controller/BackendController.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: Bug, 9.0

#3870 BUGFIX: Remove workspace creation from `EditorContentStreamZookeeper`
  Classes/Controller/BackendController.php
Labels: Bug, 9.0

#3875 BUGFIX: Skip `null` when publishing nodes
  Classes/Controller/BackendServiceController.php
Labels: Bug, 8.3

#3878 TASK: Show changes to nodeAggregates for occupied nodes dimensionspacepoints
  Classes/ContentRepository/Service/WorkspaceService.php
Labels: 9.0, Task

#3880 BUGIFX: Show hidden state only for directly disabled nodes without inheritance
  Classes/Domain/Service/NodePropertyConverterService.php
Labels: 9.0

#3872 TASK: further fix e2e test cases for Neos 9
  Tests/IntegrationTests/docker-compose.neos-dev-instance.yaml
  Tests/IntegrationTests/pageModel.js
  Tests/IntegrationTests/start-neos-dev-instance.sh
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/DimensionSelector.js
Labels: 9.0, Task
