Repository neos/neos-ui, pull requests merged in 2024-01, with the labels that each got.

#3302 FEATURE: adjust image editor to allow a custom upload screen component
  packages/neos-ui-editors/src/Editors/AssetEditor/index.js
  packages/neos-ui-editors/src/Editors/Image/index.js
Labels: Feature, Wrong Branch, 8.4

#3683 TASK: Fix StyleCI issue in NodePropertyConverterService
  Classes/Domain/Service/NodePropertyConverterService.php
Labels: 9.0, Task

#3692 BUGFIX: backendValidation unsupported option validationErrorMessage
  Classes/Domain/Model/Changes/Property.php
Labels: Bug, 8.0

#3694 TASK: Remove `AppendToCollectionImplementation`
  Classes/Fusion/AppendToCollectionImplementation.php
Labels: Technical debt, 9.0, Task

#3693 BUGFIX: Fix dimension dropdown on browser zoom
  packages/neos-ui/src/Containers/PrimaryToolbar/DimensionSwitcher/style.module.css
Labels: Bug, 8.3

#3700 BUGFIX: Add ellipsis to nodeInfoView content
  packages/neos-ui-views/src/NodeInfoView/style.css
Labels: Bug, 7.3

#3698 TASK: Extract job ID from saucelabs
  .circleci/config.yml
  Build/comment-acceptance-tests.sh
Labels: 7.3, Task

#3699 BUGFIX: Prevent overlaying of upper toolbars in RichTextEditor
  packages/neos-ui-editors/src/SecondaryEditors/CKEditorWrap/index.css
Labels: Bug, 7.3

#3706 BUGFIX: Store artifacts for logs
  .circleci/config.yml
Labels: Bug, 7.3
