Repository neos/neos-ui, pull requests merged in 2024-06, with the labels that each got.

#3799 BUGFIX: `LinkEditor` placeholder now uses the custom placeholder correctly
  packages/neos-ui-editors/src/Library/LinkInput.js
Labels: Bug, 8.3

#3634 BUGFIX: Show the right error message if only child is published
  Classes/Controller/BackendServiceController.php
  Resources/Private/Translations/en/Main.xlf
Labels: Bug, 9.0

#3796 BUGFIX: findNodeToEdit() checks if the node belongs to the correct site
  Classes/Controller/BackendController.php
Labels: Bug, 8.3

#3790 TASK: Remove `__neosLegacyUiEnabled__` flag again
  Classes/Controller/BackendController.php
Labels: 9.0, Task

#3802 TASK: adjust to overhauled node uri building
  Classes/Controller/BackendController.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Feedback/Operations/Redirect.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Configuration/Settings.yaml
Labels: 9.0, Task

#3812 TASK: Update mariadb to 10.6 for e2e docker setups
  Tests/IntegrationTests/docker-compose.neos-dev-instance.yaml
  Tests/IntegrationTests/docker-compose.yaml
Labels: 9.0, Task

#3784 TASK: Adjust to `Node:$nodeType` removal
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/NodeCreated.php
  Classes/Infrastructure/ContentRepository/CreationDialog/PromotedElementsCreationHandlerFactory.php
  Classes/Infrastructure/Neos/UriPathSegmentNodeCreationHandlerFactory.php
Labels: 9.0, Task

#3801 TASK: Upgrade to FontAwesome 6.5.2
  .yarn/cache/@fortawesome-fontawesome-common-types-npm-0.2.35-a8f9310e14-fc5e0e9182.zip
  .yarn/cache/@fortawesome-fontawesome-common-types-npm-6.5.2-3062ecb730-8164f3e166.zip
  .yarn/cache/@fortawesome-fontawesome-svg-core-npm-1.2.35-5d06f1c1f2-eccb31d2d0.zip
  .yarn/cache/@fortawesome-fontawesome-svg-core-npm-6.5.2-43d83ee9e6-f0c2a08000.zip
  .yarn/cache/@fortawesome-free-brands-svg-icons-npm-5.15.3-ebacfdf66f-03d65f66de.zip
  .yarn/cache/@fortawesome-free-brands-svg-icons-npm-6.5.2-c0e6a51bfc-f037c15978.zip
  .yarn/cache/@fortawesome-free-regular-svg-icons-npm-5.15.3-4feb2f9b89-4f713dbf83.zip
  .yarn/cache/@fortawesome-free-regular-svg-icons-npm-6.5.2-05536928ce-e5a6cf019e.zip
  .yarn/cache/@fortawesome-free-solid-svg-icons-npm-5.15.3-2a340e3cd8-5df2a837a3.zip
  .yarn/cache/@fortawesome-free-solid-svg-icons-npm-6.5.2-24587ff7e2-f23964434c.zip
  .yarn/cache/@fortawesome-react-fontawesome-npm-0.1.14-a74287f90f-fba8ee619a.zip
  .yarn/cache/@fortawesome-react-fontawesome-npm-0.2.2-e1863961b2-e4bed35bfb.zip
  Resources/Private/Translations/es/Main.xlf
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  Tests/IntegrationTests/TestDistribution/composer.json
  Tests/IntegrationTests/e2e.sh
  packages/debug-reason-for-rendering/package.json
  packages/jest-preset-neos-ui/package.json
  packages/neos-ts-interfaces/package.json
  packages/neos-ui-backend-connector/package.json
  packages/neos-ui-build/package.json
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui-constants/package.json
  packages/neos-ui-containers/package.json
  packages/neos-ui-contentrepository/package.json
  packages/neos-ui-decorators/package.json
  packages/neos-ui-editors/package.json
  packages/neos-ui-extensibility-webpack-adapter/package.json
  packages/neos-ui-extensibility/package.json
  packages/neos-ui-guest-frame/package.json
  packages/neos-ui-i18n/package.json
  packages/neos-ui-inspector/package.json
  packages/neos-ui-redux-store/package.json
  packages/neos-ui-sagas/package.json
  packages/neos-ui-validators/package.json
  packages/neos-ui-views/package.json
  packages/neos-ui/package.json
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/style.module.css
  packages/positional-array-sorter/package.json
  packages/react-proptypes/package.json
  packages/react-ui-components/package.json
  packages/react-ui-components/src/Icon/__snapshots__/fontAwesomeIcon.spec.tsx.snap
  packages/react-ui-components/src/Icon/icon.tsx
  packages/react-ui-components/src/SelectBox_HeaderWithSearchInput/style.module.css
  packages/utils-helpers/package.json
  packages/utils-logger/package.json
  packages/utils-redux/package.json
  yarn.lock
Labels: Task, 8.4

#3814 TASK: Dont use deprecated `Node::getLabel`
  Classes/Application/SyncWorkspace/Conflicts.php
  Classes/Application/SyncWorkspace/ConflictsBuilder.php
  Classes/Application/SyncWorkspace/SyncWorkspaceCommandHandler.php
Labels: 9.0, Task

#3786 FEATURE: Level up to PHPStan 8
  Classes/Application/SyncWorkspace/ConflictsBuilder.php
  Classes/Application/SyncWorkspace/SyncWorkspaceCommand.php
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/ChangeInterface.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/Create.php
  Classes/Domain/Model/Changes/CreateAfter.php
  Classes/Domain/Model/Changes/CreateBefore.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/Domain/Model/RenderedNodeDomAddress.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Classes/TypeConverter/ChangeCollectionConverter.php
  phpstan.neon.dist
Labels: Feature, 9.0

#3809 BUGFIX: Let document tree searchbox scale with sidebar width
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/style.module.css
Labels: Bug, 8.3

#3818 BUGFIX: Adjust route to workspace module
  Classes/Infrastructure/MVC/RoutesProvider.php
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
Labels: Bug, 9.0
