Repository neos/neos-ui, pull requests merged in 2024-03, with the labels that each got.

#3729 TASK: Migrate export `migratePropertiesToUnset`
  Tests/IntegrationTests/TestDistribution/Configuration/Settings.yaml
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.OneDimension/Resources/Private/Content/events.jsonl
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.TwoDimensions/Resources/Private/Content/events.jsonl
  Tests/IntegrationTests/e2e-docker.sh
  Tests/IntegrationTests/e2e.sh
Labels: 9.0, Task

#3739 BUGFIX #3671: add check if custom ratios for images are allowed
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/AspectRatioDropDown/index.js
  packages/neos-ui-editors/src/SecondaryEditors/ImageCropper/index.js
Labels: 8.3

#3740 FEATURE: move user menu to left drawer
  packages/neos-ui/src/Containers/Drawer/UserDropDown/RestoreButtonItem.js
  packages/neos-ui/src/Containers/Drawer/UserDropDown/UserImage.js
  packages/neos-ui/src/Containers/Drawer/UserDropDown/index.js
  packages/neos-ui/src/Containers/Drawer/UserDropDown/style.module.css
  packages/neos-ui/src/manifest.containers.js
Labels: Feature, 9.0

#3737 BUGFIX: Use 12/24 hour format for DateTimePicker depending on configured `format`
  packages/neos-ui-editors/src/Editors/DateTime/helpers.js
  packages/neos-ui-editors/src/Editors/DateTime/index.js
  packages/react-ui-components/src/DateInput/__snapshots__/dateInput.spec.tsx.snap
  packages/react-ui-components/src/DateInput/dateInput.spec.tsx
  packages/react-ui-components/src/DateInput/dateInput.tsx
Labels: Bug, 8.3

#3736 BUGFIX: Remove duplicated apply button in DateInput & handle onChange on date selection
  packages/neos-ui-editors/src/Editors/DateTime/index.js
  packages/react-ui-components/src/DateInput/__snapshots__/dateInput.spec.tsx.snap
  packages/react-ui-components/src/DateInput/dateInput.spec.tsx
  packages/react-ui-components/src/DateInput/dateInput.tsx
Labels: Bug, 8.3

#3661 Workspace aware commands
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
Labels: 9.0

#3754 TASK: Adjust to removal of `workspaceName` in `NodeIdToPublishOrDiscard`
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendServiceController.php
Labels: 9.0, Task

#3741 TASK: Adjust to introduced Subtree Tags
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0, Task

#3519 !!! FEATURE: Overhaul `NodeCreationHandlerInterface`
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/NodeCreation/NodeCreationCommands.php
  Classes/Domain/NodeCreation/NodeCreationElements.php
  Classes/Domain/NodeCreation/NodeCreationHandlerFactoryInterface.php
  Classes/Domain/NodeCreation/NodeCreationHandlerInterface.php
  Classes/Domain/Service/NodePropertyConversionService.php
  Classes/Infrastructure/ContentRepository/CreationDialog/CreationDialogNodeTypePostprocessor.php
  Classes/Infrastructure/ContentRepository/CreationDialog/PromotedElementsCreationHandlerFactory.php
  Classes/Infrastructure/Neos/UriPathSegmentNodeCreationHandlerFactory.php
  Classes/NodeCreationHandler/ContentTitleNodeCreationHandler.php
  Classes/NodeCreationHandler/CreationDialogPropertiesCreationHandler.php
  Classes/NodeCreationHandler/DocumentTitleNodeCreationHandler.php
  Classes/NodeCreationHandler/NodeCreationHandlerInterface.php
  Classes/Service/PublishingService.php
  Configuration/NodeTypes.yaml
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/Classes/NodeCreationHandler/ImagePropertyNodeCreationHandler.php
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/NodeTypes/Document/PageWithImage.yaml
  Tests/IntegrationTests/TestDistribution/composer.json
  Tests/Unit/CreationDialogNodeTypePostprocessorTest.php
Labels: Feature, 9.0

#3747 BUGFIX: Disable node text selection in document tree
  esbuild.js
  packages/react-ui-components/src/Tree/tree.module.css
Labels: Bug, 8.3

#3720 BUGFIX Fix conversion in CreationDialogPropertiesCreationHandler
  Classes/NodeCreationHandler/CreationDialogPropertiesCreationHandler.php
Labels: 8.3

#3717 TASK: Move `ContentRepositoryId` to `SharedModel` namespace
  Classes/ContentRepository/Service/NeosUiNodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/InitialData/InitialStateProviderInterface.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/Fusion/Helper/ContentDimensionsHelper.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Classes/Infrastructure/Configuration/InitialStateProvider.php
  Classes/TypeConverter/ChangeCollectionConverter.php
Labels: 9.0, Task

#3753 BUGFIX: Correctly append cache buster value to existing query parameters for included CSS & JS
  Classes/Domain/Service/StyleAndJavascriptInclusionService.php
Labels: Bug, 8.3
