Repository neos/neos-ui, pull requests merged in 2024-05, with the labels that each got.

#3775 TASK: Adjust to workspace aware `ContentGraph`
  Classes/Application/ReloadNodes/ReloadNodesQueryHandler.php
  Classes/ContentRepository/Service/NeosUiNodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
Labels: 9.0, Task

#3776 TASK: Dont add useless node names on copy
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
Labels: 9.0, Task

#3503 BUGFIX: Reflect discard of node move changes correctly in the UI
  Classes/ContentRepository/Service/NodeService.php
  Classes/Controller/BackendServiceController.php
  Classes/TypeConverter/ChangeCollectionConverter.php
  Tests/IntegrationTests/Fixtures/1Dimension/issue-3184.e2e.js
  Tests/IntegrationTests/TestDistribution/composer.json
Labels: Bug, 8.3

#3734 BUGFIX: document-node is redirected to the nearest parent on workspace change
  Classes/Controller/BackendServiceController.php
Labels: Bug, 8.3

#3779 TASK: Ease upmerging by avoiding version conflicts
  .github/workflows/build_and_test.yml
  Build/Jenkins/release-neos-ui.sh
  Makefile
  package.json
  packages/debug-reason-for-rendering/package.json
  packages/jest-preset-neos-ui/package.json
  packages/neos-ts-interfaces/package.json
  packages/neos-ui-backend-connector/package.json
  packages/neos-ui-build/package.json
  packages/neos-ui-ckeditor5-bindings/package.json
  packages/neos-ui-constants/package.json
  packages/neos-ui-containers/package.json
  packages/neos-ui-contentrepository/package.json
  packages/neos-ui-decorators/package.json
  packages/neos-ui-editors/package.json
  packages/neos-ui-extensibility-webpack-adapter/package.json
  packages/neos-ui-extensibility/package.json
  packages/neos-ui-guest-frame/package.json
  packages/neos-ui-i18n/package.json
  packages/neos-ui-inspector/package.json
  packages/neos-ui-redux-store/package.json
  packages/neos-ui-sagas/package.json
  packages/neos-ui-validators/package.json
  packages/neos-ui-views/package.json
  packages/neos-ui/package.json
  packages/positional-array-sorter/package.json
  packages/react-proptypes/package.json
  packages/react-ui-components/package.json
  packages/utils-helpers/package.json
  packages/utils-logger/package.json
  packages/utils-redux/package.json
Labels: 8.3, Task

#3772 TASK: Adjust to `NodeLabelRenderer`
  Classes/Domain/Model/Feedback/Operations/Redirect.php
  Classes/Domain/Model/Feedback/Operations/RemoveNode.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Tests/Unit/CreationDialogNodeTypePostprocessorTest.php
Labels: 9.0, Task

#3735 TASK: Adjust to changes in Neos removing internal node properties
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0, Task

#3780 BUGFIX: Add missing closing tag
  Resources/Private/Translations/es/Main.xlf
Labels: Bug, 9.0

#3777 TASK Refactor to not use content subgraph identity
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/Create.php
  Classes/Domain/Model/Changes/CreateAfter.php
  Classes/Domain/Model/Changes/CreateBefore.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/NodeCreated.php
  Classes/Domain/Model/Feedback/Operations/Redirect.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RemoveNode.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
  Classes/Domain/Model/Feedback/Operations/UpdateWorkspaceInfo.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: 9.0

#3782 TASK: Adjust To Tethered NodeType Definitions
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/Create.php
  Classes/Domain/Model/Changes/CreateAfter.php
  Classes/Domain/Model/Changes/CreateBefore.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
Labels: 9.0, Task

#3783 TASK: Adjust to neos 9 deprecations
  Classes/Application/ReloadNodes/ReloadNodesQueryHandler.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/InitialData/InitialStateProviderInterface.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
  Classes/Domain/Model/Changes/CreateAfter.php
  Classes/Domain/Model/Changes/CreateBefore.php
  Classes/Domain/Model/Changes/MoveAfter.php
  Classes/Domain/Model/Changes/MoveBefore.php
  Classes/Domain/Model/Changes/MoveInto.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Domain/Model/Feedback/Operations/NodeCreated.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/ReloadDocument.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/NodeCreation/NodeCreationCommands.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/FlowQueryOperations/NeosUiDefaultNodesOperation.php
  Classes/FlowQueryOperations/NeosUiFilteredChildrenOperation.php
  Classes/FlowQueryOperations/SearchOperation.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Infrastructure/Configuration/InitialStateProvider.php
  Configuration/Settings.yaml
Labels: 9.0, Task

#3788 TASK: Adjust to workspace name in events
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.OneDimension/Resources/Private/Content/events.jsonl
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.Test.TwoDimensions/Resources/Private/Content/events.jsonl
Labels: 9.0, Task
