Repository neos/neos-ui, pull requests merged in 2024-02, with the labels that each got.

#3682 !!!FEATURE: Reform foundation and boot process of the UI
  Classes/Controller/BackendController.php
  Classes/Domain/InitialData/CacheConfigurationVersionProviderInterface.php
  Classes/Domain/InitialData/ConfigurationProviderInterface.php
  Classes/Domain/InitialData/FrontendConfigurationProviderInterface.php
  Classes/Domain/InitialData/InitialStateProviderInterface.php
  Classes/Domain/InitialData/MenuProviderInterface.php
  Classes/Domain/InitialData/NodeTypeGroupsAndRolesProviderInterface.php
  Classes/Domain/InitialData/RoutesProviderInterface.php
  Classes/Domain/Service/StyleAndJavascriptInclusionService.php
  Classes/Infrastructure/Cache/CacheConfigurationVersionProvider.php
  Classes/Infrastructure/Configuration/ConfigurationProvider.php
  Classes/Infrastructure/Configuration/FrontendConfigurationProvider.php
  Classes/Infrastructure/Configuration/InitialStateProvider.php
  Classes/Infrastructure/ContentRepository/NodeTypeGroupsAndRolesProvider.php
  Classes/Infrastructure/MVC/RoutesProvider.php
  Classes/Infrastructure/MVC/RoutesProviderHelper.php
  Classes/Infrastructure/Neos/MenuProvider.php
  Classes/Presentation/ApplicationView.php
  Configuration/Objects.yaml
  Configuration/Settings.yaml
  Configuration/Views.yaml
  Resources/Private/Fusion/Backend/Component/ModuleMenu.fusion
  Resources/Private/Fusion/Backend/Root.fusion
  Resources/Private/Templates/Backend/Index.html
  Resources/Private/Templates/Backend/Partials/SplashScreen.html
  packages/neos-ui-redux-store/src/System/index.spec.js
  packages/neos-ui-redux-store/src/System/index.ts
  packages/neos-ui/src/System/index.js
  packages/neos-ui/src/System/terminateDueToFatalInitializationError.js
  packages/neos-ui/src/index.js
  packages/utils-helpers/src/delay.spec.js
  packages/utils-helpers/src/delay.ts
  packages/utils-helpers/src/discover.spec.js
  packages/utils-helpers/src/discover.ts
  packages/utils-helpers/src/index.ts
Labels: 9.0

#3701 BUGFIX: Resolve issue with custom data source displaying additional l…
  packages/react-ui-components/src/SelectBox_Option_MultiLineWithThumbnail/style.css
Labels: Bug, 7.3

#3705 TASK: Upgrade Node.js to version 20 LTS
  .circleci/config.yml
  .nvmrc
  package.json
Labels: 8.3, Task

#3710 TASK: Fix phpstan error and add `composer run lint:phpstan`
  .circleci/config.yml
  Classes/Fusion/ExceptionHandler/PageExceptionHandler.php
  composer.json
  phpstan.neon.dist
Labels: 9.0, Task

#3681 FEATURE Add timeable node visibility
  Classes/Fusion/Helper/NodeInfoHelper.php
  packages/neos-ui/package.json
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
  yarn.lock
Labels: 9.0

#3703 TASK: Avoid heavily use of controller context and make `Neos.Ui.NodeInfo` internal
  Classes/Controller/BackendController.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/InitialData/FrontendConfigurationProviderInterface.php
  Classes/Domain/InitialData/InitialStateProviderInterface.php
  Classes/Domain/InitialData/MenuProviderInterface.php
  Classes/Domain/Model/Feedback/Operations/ReloadDocument.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodeInfo.php
  Classes/Domain/Model/Feedback/Operations/UpdateNodePreviewUrl.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Fusion/RenderConfigurationImplementation.php
  Classes/Infrastructure/Configuration/FrontendConfigurationProvider.php
  Classes/Infrastructure/Configuration/InitialStateProvider.php
  Classes/Infrastructure/Neos/MenuProvider.php
  Configuration/Settings.yaml
Labels: 9.0, Task

#3711 TASK: Cleanup, remove or declare EEL helpers as internal
  Classes/Fusion/Helper/ApiHelper.php
  Classes/Fusion/Helper/ContentDimensionsHelper.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Fusion/Helper/PositionalArraySorterHelper.php
  Classes/Fusion/Helper/RenderingModeHelper.php
  Classes/Fusion/Helper/StaticResourcesHelper.php
  Classes/Fusion/Helper/WorkspaceHelper.php
  Configuration/Settings.yaml
Labels: 9.0, Task

#3686 TASK: 4621 adjust to uriPathSegment change
  Configuration/NodeTypes.yaml
  Tests/IntegrationTests/Fixtures/1Dimension/inspector.e2e.js
  Tests/IntegrationTests/Fixtures/1Dimension/inspectorValidation.e2e.js
Labels: 9.0, Task

#3689 !!! TASK: Removes Editors for plugins
  Classes/Infrastructure/MVC/RoutesProvider.php
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-editors/src/Editors/MasterPlugin/index.js
  packages/neos-ui-editors/src/Editors/PluginView/index.js
  packages/neos-ui-editors/src/Editors/PluginViews/index.js
  packages/neos-ui-editors/src/Editors/PluginViews/style.module.css
  packages/neos-ui-editors/src/Editors/index.js
  packages/neos-ui-editors/src/index.js
  packages/neos-ui-editors/src/manifest.js
Labels: Cleanup, 9.0
