Repository neos/neos-ui, pull requests merged in 2024-07, with the labels that each got.

#3745 BUGFIX: Select box shows invalid value
  Resources/Private/Translations/de/Main.xlf
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ui-editors/src/Editors/SelectBox/DataSourceBasedSelectBoxEditor.js
  packages/neos-ui-editors/src/Editors/SelectBox/SelectBoxHelpers.js
  packages/neos-ui-editors/src/Editors/SelectBox/SimpleSelectBoxEditor.js
  packages/neos-ui-editors/src/Editors/SelectBox/selectBoxHelpers.spec.ts
  packages/neos-ui-editors/src/Editors/SelectBox/selectBoxHelpers.ts
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/index.js
  packages/react-ui-components/src/MultiSelectBox_ListPreviewSortable/multiSelectBox_ListPreviewSortable.js
  packages/react-ui-components/src/SelectBox/__snapshots__/selectBox.spec.js.snap
  packages/react-ui-components/src/SelectBox/selectBox.js
Labels: Bug, 8.3

#3810 FEATURE: Separated references and properties in Neos UI
  packages/neos-ts-interfaces/src/index.ts
  packages/neos-ui-contentrepository/src/registry/NodeTypesRegistry.ts
Labels: Feature, 9.0

#3821 FEATURE: Allow to set maximum rows to restrict height of the textarea editor in inspector
  packages/neos-ui-editors/src/Editors/TextArea/index.js
  packages/react-ui-components/src/TextArea/textArea.tsx
Labels: Feature, 8.4

#3819 TASK: adjust to Command Api changes in Neos
  Classes/Domain/Model/Changes/AbstractCreate.php
  Classes/Domain/Model/Changes/CopyAfter.php
  Classes/Domain/Model/Changes/CopyBefore.php
  Classes/Domain/Model/Changes/CopyInto.php
Labels: 9.0, Task

#3751 BUGFIX: Change update interval on CKEditor
  Tests/IntegrationTests/Fixtures/1Dimension/createNewNodes.e2e.js
  packages/neos-ui-ckeditor5-bindings/src/ckEditorApi.js
Labels: Bug, 8.3

#3825 BUGFIX Fix Neos.Ui version information in build script
  Build/Jenkins/release-neos-ui.sh
  Build/Jenkins/update-neos-ui-compiled.sh
  Makefile
  esbuild.js
Labels: 8.3

#3823 Add float case handling to NodePropertyConversionService
  Classes/Domain/Service/NodePropertyConversionService.php
Labels: 9.0

#3833 BUGFIX: Prevent unneccessary server calls when inline editor is unchanged
  packages/neos-ui-guest-frame/src/initializePropertyDomNode.js
Labels: Bug, 8.3

#3822 BUGFIX: Fix inconsistencies in document tree with node tree presets
  Classes/Controller/BackendServiceController.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Tests/IntegrationTests/Fixtures/1Dimension/SitePackage/Resources/Private/Content/Sites.xml
  Tests/IntegrationTests/Fixtures/1Dimension/nodeTreePresets.e2e.js
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/Application/RemoveAdditionalSettings/Controller/RemoveAdditionalSettingsController.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/Application/RemoveAdditionalSettings/RemoveAdditionalSettingsCommand.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/Application/RemoveAdditionalSettings/RemoveAdditionalSettingsCommandHandler.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/Application/WriteAdditionalSettings/Controller/WriteAdditionalSettingsController.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/Application/WriteAdditionalSettings/WriteAdditionalSettingsCommand.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/Application/WriteAdditionalSettings/WriteAdditionalSettingsCommandHandler.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/Policy.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/Routes.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/Configuration/Settings.Neos.Flow.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Document/Blog.yaml
  Tests/IntegrationTests/SharedNodeTypesPackage/NodeTypes/Document/BlogArticle.yaml
  Tests/IntegrationTests/pageModel.js
  packages/neos-ui-backend-connector/src/FlowQuery/Operations/GetForTreeWithParents/index.ts
  packages/neos-ui-redux-store/src/CR/Nodes/index.ts
  packages/neos-ui-redux-store/src/UI/PageTree/index.spec.js
  packages/neos-ui-redux-store/src/UI/PageTree/index.ts
  packages/neos-ui-redux-store/src/UI/PageTree/selectors.ts
  packages/neos-ui-sagas/src/CR/NodeOperations/moveDroppedNode.js
  packages/neos-ui-sagas/src/CR/NodeOperations/moveDroppedNodes.js
  packages/neos-ui-sagas/src/CR/NodeOperations/reloadState.js
  packages/neos-ui-sagas/src/UI/PageTree/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/Node/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeFilter/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/NodeTreeSearchInput/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTreeSearchBar/index.js
  packages/react-ui-components/src/DropDown/contents.tsx
  packages/react-ui-components/src/DropDown/header.tsx
  packages/react-ui-components/src/DropDown/wrapper.tsx
  packages/react-ui-components/src/SelectBox/selectBox.js
  packages/react-ui-components/src/SelectBox_Header/selectBox_Header.js
  packages/react-ui-components/src/Tree/node.module.css
Labels: Bug, 8.3
