Repository neos/neos-ui, pull requests merged in 2024-04, with the labels that each got.

#3752 FEATURE: Refactor publication and discarding endpoints
  Classes/Application/ChangeTargetWorkspace.php
  Classes/Application/DiscardChangesInDocument.php
  Classes/Application/DiscardChangesInSite.php
  Classes/Application/PublishChangesInDocument.php
  Classes/Application/PublishChangesInSite.php
  Classes/Application/SyncWorkspace.php
  Classes/ContentRepository/Service/NeosUiNodeService.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendServiceController.php
  Classes/Domain/Model/Changes/Remove.php
  Classes/Infrastructure/MVC/RoutesProvider.php
  Classes/Service/PublishingService.php
  Configuration/Routes.Service.yaml
  Tests/IntegrationTests/TestDistribution/composer.json
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-redux-store/src/CR/Nodes/index.ts
  packages/neos-ui-redux-store/src/CR/Nodes/selectors.ts
  packages/neos-ui-redux-store/src/CR/Workspaces/index.spec.js
  packages/neos-ui-redux-store/src/CR/Workspaces/index.ts
  packages/neos-ui-redux-store/src/CR/index.ts
  packages/neos-ui-redux-store/src/UI/index.ts
  packages/neos-ui-redux-store/src/User/index.ts
  packages/neos-ui-redux-store/src/index.ts
  packages/neos-ui-sagas/src/CR/NodeOperations/reloadState.js
  packages/neos-ui-sagas/src/Publish/index.js
  packages/neos-ui/src/Containers/Modals/DiscardDialog/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
Labels: Feature, 9.0

#3668 TASK: Adjust to split up references and properties
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/NodeCreation/NodeCreationElements.php
  Classes/Domain/Service/NodePropertyConversionService.php
  Classes/Domain/Service/NodePropertyConverterService.php
  Classes/Infrastructure/ContentRepository/CreationDialog/CreationDialogNodeTypePostprocessor.php
  Classes/Infrastructure/ContentRepository/CreationDialog/PromotedElementsCreationHandlerFactory.php
  Tests/Unit/CreationDialogNodeTypePostprocessorTest.php
Labels: 9.0, Task

#3708 BUGFIX: Insert copied or moved nodes in order of selection
  Classes/Domain/Model/Changes/CopyInto.php
  packages/neos-ui-redux-store/src/CR/Nodes/helpers.ts
  packages/neos-ui-sagas/src/CR/NodeOperations/pasteNode.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
Labels: Bug, 8.3

#3763 BUGFIX: Copy nodetype name from nodeinfoview without hyphens
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ui-views/src/NodeInfoView/index.js
  packages/neos-ui-views/src/NodeInfoView/style.module.css
Labels: Bug, 8.3

#3756 FEATURE: Collapse All Button in Content and Page Tree
  Resources/Private/Translations/de/Main.xlf
  Resources/Private/Translations/en/Main.xlf
  packages/neos-ui-redux-store/src/CR/Nodes/selectors.ts
  packages/neos-ui-redux-store/src/UI/ContentTree/index.ts
  packages/neos-ui-redux-store/src/UI/PageTree/index.ts
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/index.js
  packages/neos-ui/src/Containers/LeftSideBar/NodeTree/style.module.css
Labels: Feature, 8.4

#3758 TASK: Adjust to `ViewInterface` change in Neos.Flow and Neos.Neos
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Fusion/ExceptionHandler/PageExceptionHandler.php
  Classes/Presentation/ApplicationView.php
  Classes/View/OutOfBandRenderingCapable.php
Labels: 9.0, Task

#3759 !!!FEATURE: Lock the UI and present a modal during publish/discard
  .editorconfig
  Classes/Application/ReloadNodes/MinimalNodeForTree.php
  Classes/Application/ReloadNodes/NoDocumentNodeWasFound.php
  Classes/Application/ReloadNodes/NoSiteNodeWasFound.php
  Classes/Application/ReloadNodes/NodeMap.php
  Classes/Application/ReloadNodes/NodeMapBuilder.php
  Classes/Application/ReloadNodes/ReloadNodesQuery.php
  Classes/Application/ReloadNodes/ReloadNodesQueryHandler.php
  Classes/Application/ReloadNodes/ReloadNodesQueryResult.php
  Classes/ContentRepository/Service/WorkspaceService.php
  Classes/Controller/BackendServiceController.php
  Classes/Infrastructure/MVC/RoutesProvider.php
  Configuration/Routes.Service.yaml
  Configuration/Settings.yaml
  Resources/Private/Translations/en/Error.xlf
  Resources/Private/Translations/en/PublishingDialog.xlf
  Tests/IntegrationTests/Fixtures/1Dimension/discarding.e2e.js
  Tests/IntegrationTests/TestDistribution/composer.json
  Tests/IntegrationTests/utils.js
  packages/neos-ui-backend-connector/src/Endpoints/index.ts
  packages/neos-ui-backend-connector/src/index.ts
  packages/neos-ui-error/README.md
  packages/neos-ui-error/package.json
  packages/neos-ui-error/src/ErrorView.tsx
  packages/neos-ui-error/src/index.ts
  packages/neos-ui-error/src/style.module.css
  packages/neos-ui-error/src/types.ts
  packages/neos-ui-redux-store/package.json
  packages/neos-ui-redux-store/src/CR/Publishing/index.ts
  packages/neos-ui-redux-store/src/CR/Workspaces/index.spec.js
  packages/neos-ui-redux-store/src/CR/Workspaces/index.ts
  packages/neos-ui-redux-store/src/CR/index.ts
  packages/neos-ui-redux-store/src/UI/Remote/index.spec.js
  packages/neos-ui-redux-store/src/UI/Remote/index.ts
  packages/neos-ui-redux-store/src/UI/index.ts
  packages/neos-ui-redux-store/src/User/index.ts
  packages/neos-ui-redux-store/src/index.ts
  packages/neos-ui-sagas/src/CR/NodeOperations/index.js
  packages/neos-ui-sagas/src/CR/NodeOperations/reloadNodes.ts
  packages/neos-ui-sagas/src/CR/Workspaces/index.ts
  packages/neos-ui-sagas/src/Publish/index.js
  packages/neos-ui-sagas/src/Publish/index.ts
  packages/neos-ui-sagas/src/manifest.js
  packages/neos-ui/package.json
  packages/neos-ui/src/Containers/Modals/DiscardDialog/index.js
  packages/neos-ui/src/Containers/Modals/DiscardDialog/style.module.css
  packages/neos-ui/src/Containers/Modals/PublishingDialog/ConfirmationDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/Diagram.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/ProcessIndicator.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/PublishingDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/ResultDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/index.ts
  packages/neos-ui/src/Containers/Modals/PublishingDialog/style.module.css
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
  packages/neos-ui/src/manifest.containers.js
  yarn.lock
Labels: 9.0

#3748 BUGFIX: 9.0 infinite (real) reloads after exception
  Classes/Fusion/Helper/NodeInfoHelper.php
Labels: Bug, 9.0
