Repository neos/neos-ui, pull requests merged in 2025-01, with the labels that each got.

#3904 TASK: Update workspace review URL
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
Labels: 9.0, Task

#3907 BUGFIX: Forgiving `I18nRegistry.translate` for strings with colons and `undefined`
  packages/neos-ui-i18n/README.md
  packages/neos-ui-i18n/src/component/I18n.tsx
  packages/neos-ui-i18n/src/global/globals.spec.ts
  packages/neos-ui-i18n/src/global/globals.ts
  packages/neos-ui-i18n/src/model/TranslationAddress.spec.ts
  packages/neos-ui-i18n/src/model/TranslationAddress.ts
  packages/neos-ui-i18n/src/registry/I18nRegistry.spec.ts
  packages/neos-ui-i18n/src/registry/I18nRegistry.ts
  packages/neos-ui-i18n/src/registry/getTranslationAddress.spec.ts
  packages/neos-ui-i18n/src/registry/getTranslationAddress.ts
  packages/neos-ui-i18n/src/translate.ts
Labels: Bug, 9.0

#3909 FEATURE: Simplify publish workflow
  Tests/IntegrationTests/Fixtures/1Dimension/syncing.e2e.js
  packages/neos-ui-redux-store/src/CR/Publishing/index.ts
  packages/neos-ui-sagas/src/Publish/index.ts
  packages/neos-ui-sagas/src/Sync/index.ts
  packages/neos-ui/src/Containers/Modals/PublishingDialog/ConfirmationDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/PublishingDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/ResultDialog.tsx
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/index.js
  packages/neos-ui/src/Containers/PrimaryToolbar/PublishDropDown/style.module.css
Labels: Feature, 9.0
