Repository neos/neos-ui, pull requests merged in 2025-04, with the labels that each got.

#3934 TASK: Fix PHP 8.4 deprecations
  Classes/Aspects/AugmentationAspect.php
  Classes/ContentRepository/Service/NodeService.php
  Classes/Controller/BackendController.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Domain/Service/NodeTreeBuilder.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/TypeConverter/ChangeCollectionConverter.php
  Classes/TypeConverter/UiDependentImageSerializer.php
  Tests/IntegrationTests/SharedNodeTypesPackage/Classes/DataSources/NodeWithDependingPropertiesDataSource.php
Labels: 8.3, Task

#3915 BUGFIX: Render cke toolbar table dropdowns with data urls
  packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/icons/index.js
  packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/icons/table-column.dataurl.svg
  packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/icons/table-merge-cell.dataurl.svg
  packages/neos-ui-ckeditor5-bindings/src/EditorToolbar/icons/table-row.dataurl.svg
Labels: Bug, 8.3

#3828 FEATURE: Make RightSideBar inspector resizable
  packages/neos-ui/src/Containers/RightSideBar/Inspector/style.module.css
  packages/neos-ui/src/Containers/RightSideBar/style.module.css
Labels: Feature, 8.4

#3913 BUGFIX: Non-scrollable Neos.Neos/Inspector/Editors/RichTextEditor
  packages/neos-ui-editors/src/SecondaryEditors/CKEditorWrap/index.module.css
Labels: Bug, 8.3

#3874 Feature/3715 rebased make multi select box drag&drop sorting feature optional
  packages/react-ui-components/src/MultiSelectBox/__snapshots__/multiSelectBox.spec.js.snap
  packages/react-ui-components/src/MultiSelectBox/multiSelectBox.js
  packages/react-ui-components/src/MultiSelectBox_ListPreviewSortable/multiSelectBox_ListPreviewSortable.js
  packages/react-ui-components/src/MultiSelectBox_ListPreviewSortable_DraggableListPreviewElement/multiSelectBox_ListPreviewSortable_DraggableListPreviewElement.js
Labels: 8.4

#3935 TASK: Upmerge 8.4 into 9.0
  Classes/Controller/BackendController.php
  Classes/Domain/Model/AbstractChange.php
  Classes/Domain/Model/Changes/AbstractStructuralChange.php
  Classes/Domain/Model/Changes/Property.php
  Classes/Domain/Model/Feedback/Messages/Warning.php
  Classes/Domain/Model/Feedback/Operations/ReloadContentOutOfBand.php
  Classes/Domain/Model/Feedback/Operations/RenderContentOutOfBand.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Tests/IntegrationTests/TestDistribution/DistributionPackages/Neos.TestNodeTypes/Classes/DataSources/NodeWithDependingPropertiesDataSource.php
  packages/neos-ui-error/src/container/FlashMessages/FlashMessage.tsx
  packages/neos-ui-error/src/container/FlashMessages/style.module.css
  packages/neos-ui-error/src/types.ts
  packages/neos-ui/src/manifest.js
Labels: 9.0, Task

#3893 FEATURE: Add "publish all" dialog for partial publish error
  Classes/Application/PublishChangesInDocument/PublishChangesInDocumentCommandHandler.php
  Classes/Application/PublishChangesInSite/PublishChangesInSiteCommandHandler.php
  Classes/Application/Shared/PartialConflictsOccurred.php
  Classes/Application/SyncWorkspace/SyncWorkspaceCommandHandler.php
  Classes/Infrastructure/ContentRepository/ConflictsFactory.php
  Resources/Private/Translations/en/PublishingDialog.xlf
  packages/neos-ui-redux-store/src/CR/Publishing/index.ts
  packages/neos-ui-sagas/src/Publish/index.ts
  packages/neos-ui/src/Containers/Modals/PublishingDialog/Diagram.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/PartialConflictDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/PublishingDialog.tsx
  packages/neos-ui/src/Containers/Modals/PublishingDialog/style.module.css
Labels: Feature, 9.0

#3937 BUGFIX: Prevent constant re-rendering of right sidebar
  packages/neos-ui/src/Containers/RightSideBar/Inspector/index.js
  packages/react-ui-components/src/DropDown/contents.tsx
Labels: Bug, 8.3
