Repository neos/neos-ui, pull requests merged in 2025-06, with the labels that each got.

#3886 BUGFIX: Allow to insert node inside not editable content collection (via policy)
  packages/neos-ui-redux-store/src/CR/Nodes/selectors.ts
Labels: Bug, 8.3

#3954 BUGFIX: Proper error if site node not found in backend
  Classes/Controller/BackendController.php
  Classes/Domain/InitialData/InitialStateProviderInterface.php
  Classes/Fusion/Helper/NodeInfoHelper.php
  Classes/Infrastructure/Configuration/InitialStateProvider.php
Labels: Bug, 9.0

#3958 TASK: Update README.md
  README.md
Labels: 9.0, Task
